### ISSUE TITLE
Questions and Thoughts

### ISSUE THREAD

**Issue by chrisjbreisch** [Chronial/cygwin-sudo#1]
I notice that you seem to have abandoned nu774's scheduled task and sudoserver "service". It seemed to have been failing under Windows 10. Were you unable to get it working again?

Also, I notice that I can't run anything that uses a shell built-in or aliases. Is that because I'm running in python in the elevated environment and not running in bash anymore? Try "sudo alias" for example.

Looking at the code, I see some references to passing a port and password file as arguments. What's that about?

**Comment by Chronial** [comment]
> I notice that you seem to have abandoned nu774's scheduled task and sudoserver "service". It seemed to have been failing under Windows 10. Were you unable to get it working again?

This is a deliberate design decision. The scheduled task/service in its previous form was a security issue – it effectively disabled UAC completely. It also massively complicated setup. I wanted this to be easy to setup, which does not combine well with a service.

> Also, I notice that I can't run anything that uses a shell built-in or aliases. Is that because I'm running in python in the elevated environment and not running in bash anymore? Try "sudo alias" for example.

Yes, it is because `sudo` is running the command and not a shell. This is the same in actual linux `sudo`. See [here](https://unix.stackexchange.com/questions/148545/why-does-sudo-ignore-aliases) and [here](https://askubuntu.com/questions/22037/aliases-not-available-when-using-sudo). These threads also suggest workarounds.

> Looking at the code, I see some references to passing a port and password file as arguments. What's that about?

The tool works by starting a separate process with elevated rights. For security purposes, Windows prevents us from communicating with that process easily, so we do it via TCP – hence the port. But that would allow any local process to run a command via the elevated process, so we secure the connection with a password – hence the password.

**Comment by chrisjbreisch** [comment]
@Chronial - that all makes sense. Thanks.
